server {
    listen 80;
    server_name ${DOMAIN} www.${DOMAIN};

    include /etc/nginx/snippets/acme.conf;

    location / {
        return 301 https://${DOMAIN}$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name www.${DOMAIN};

    ssl_certificate /etc/letsencrypt/live/${CERT_NAME}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${CERT_NAME}/privkey.pem;
    include /etc/nginx/snippets/tls.conf;

    return 301 https://${DOMAIN}$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name ${DOMAIN};

    ssl_certificate /etc/letsencrypt/live/${CERT_NAME}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${CERT_NAME}/privkey.pem;
    include /etc/nginx/snippets/tls.conf;

    include /etc/nginx/snippets/site.conf;
}
